FROM python:3.11-slim

WORKDIR /app


COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt && \
    pip list | grep prometheus  # Debugowanie - pokaże czy zainstalowało


COPY app.py .


EXPOSE 8000


HEALTHCHECK --interval=30s --timeout=3s --start-period=10s --retries=3 \
    CMD python -c "import urllib.request; urllib.request.urlopen('http://localhost:8000/health').read()" || exit 1

CMD ["python", "-u", "app.py"]
